defaults:
  - flow_solver: icepack
  - flowline: basic
  - icepack_model: simple_shelf
  - ics: perfect_flowtube
  - mesh: small_2d
  - spinup: short
  - mass_balance: small_constant
  - _self_

shelf: Synthetic_2d
name: test
save_figs: True
overwrite: True